# Generated by Django 5.2.7 on 2025-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rut',
            field=models.CharField(default='99999999-K', max_length=10),
        ),
    ]
