# Generated by Django 5.2.7 on 2025-11-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tipopersona_persona_tipo_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fono',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
