# Generated by Django 5.2.7 on 2025-12-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_persona_fono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='qrcode',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
