# Generated by Django 5.2.7 on 2025-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro_externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('rut', models.CharField(max_length=10)),
                ('motivo', models.CharField(choices=[('respuesta de emergencia.', '1'), ('respuesta a solucitud.', '2'), ('visita administrativa.', '3'), ('entrega programada.', '4'), ('servicio tecnico.', '5'), ('representar organizacion.', '6'), ('consulta casual.', '7')], max_length=100)),
            ],
        ),
    ]
