# Generated by Django 5.2.7 on 2025-11-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroTactil1', '0002_rename_registro_externo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
