# Generated by Django 5.2.7 on 2025-11-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroTactil1', '0003_alter_registro_fecha_alter_registro_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='motivo',
            field=models.CharField(choices=[('respuesta de emergencia.', 'respuesta de emergencia.'), ('respuesta a solucitud.', 'respuesta a solucitud.'), ('visita administrativa.', 'visita administrativa.'), ('entrega programada.', 'entrega programada.'), ('servicio tecnico.', 'servicio tecnico.'), ('representar organizacion.', 'representar organizacion.'), ('consulta casual.', 'consulta casual.')], max_length=100),
        ),
    ]
