# Generated by Django 5.2.7 on 2025-11-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('registroTactil1', '0004_alter_registro_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='responsable',
            field=models.ManyToManyField(to='dashboard.persona'),
        ),
    ]
