# Generated by Django 5.2.7 on 2025-11-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroTactil1', '0005_registro_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='rut',
        ),
    ]
