# Generated by Django 5.2.7 on 2025-11-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tipopersona_persona_tipo_persona'),
        ('registroTactil1', '0006_remove_registro_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='responsable',
        ),
        migrations.AddField(
            model_name='registro',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.persona'),
        ),
    ]
