# Generated by Django 5.2.7 on 2025-12-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroTactil1', '0007_remove_registro_responsable_registro_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='qr_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
